### ISSUE TITLE
problems with repo

### ISSUE THREAD

**Issue by lmiq** [JuliaReach/SetPropagation-FEM-JuliaCon21#15]
I cannot open the paper.pdf linked int he README, and there is a figure with a broken link as well.

**Comment by carstenbauer** [comment]
The corresponding JuliaCon proceedings REVIEW thread containing the current article proof (PDF) is here: https://github.com/JuliaCon/proceedings-review/issues/95

**Comment by mforets** [comment]
> there is a figure with a broken link as well.

fixed, thanks.

> The corresponding JuliaCon proceedings REVIEW thread containing the current article proof (PDF) is here:

ok thanks @carstenbauer -- then perhaps adding the `paper.pdf` to this repo is not a good idea (asking since its the first time we submit to a JOSS like system)

**Comment by carstenbauer** [comment]
I would wait with adding it until the review process is finished.

**Comment by mforets** [comment]
> I would wait with adding it until the review process is finished.

Thanks for the clarification, we've updated the README correspondingly.
